version: 2
jobs:
  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
        command: |
          echo Running test
          echo "machine github.com login ajaymore password $GITHUB_TOKEN" > ~/.netrc

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website
